### ISSUE TITLE
Export should check on is_object

### ISSUE THREAD

**Issue by potibm** [gossi/swagger#10]
In AbstractModel::export() method_exists is called on each field value even when the $val is not an object.

As method_exists also takes class names this might lead to strange results (in my case an Email class is autoloaded because this value is set).

Checking for is_object first should make things smoother and faster.

**Comment by gossi** [comment]
Can you provide a test object, which I can also add to the test suite? Can be a minimal working example of yours, which is causing the problem at the moment.

**Comment by potibm** [comment]
```
class Email {
    public function toArray() {
        return '';
    }
}

$endpoint = new \gossi\swagger\Schema();

$endpoint->setDescription('Email');

var_dump($endpoint->toArray());
```

will lead to a PHP Fatal.
