### ISSUE TITLE
Make Swagger::parse() public

### ISSUE THREAD

**Issue by GuilhemN** [gossi/swagger#5]
What do you think about making `Swagger::parse()` public to allow to merge several swagger definitions ?

This way we could call `Swagger::parse()` after the object initialization with another swagger definition and maybe even choose a merging strategy (override, only if not set/default, merge).

**Comment by gossi** [comment]
No, I want to keep the `parse()` method private. However, I like your idea of merging. In current master (I'm testing this locally at the moment and it looks good) it is already possible to merge all collections that this lib containts. For example:

``` php
$swagger = Swagger::fromFile('api.json');
$anotherSwagger = new Swagger($json);

$swagger->getDefinitions()->setAll($anotherSwagger->getDefinitions());
```

I'm not sure about individual properties yet, as they are set on a let's call it "per-project" basis (e.g. the info section). So it wouldn't make sense for me to provide a merge here.

What do you think? What would you need?

**Comment by GuilhemN** [comment]
I wanted to merge several partial specifications (I wanted to generate the doc of an api with different libraries and then merge their output) but after investigating a bit more, I think you're right, they are too many edge cases so it should be better to have my own merger to do exactly what I want.
I close this PR as this is not the best thing to do :)

And your example looks good ! What about even renaming `setAll` to `addAll` or similar to be clearer ?

Thanks for taking care of this library !

**Comment by gossi** [comment]
For collections that are key-based (Maps) it is `setAll` for items (List) it is `addAll` at the moment. Similarly to their respective `set` and  `add` methods - dunno about it either, because it relates to the internal logic.

If you need more merge methods then open a PR, I'm happy to accept them since this is what I started with the collections stuff.

**Comment by GuilhemN** [comment]
@gossi ok makes sense :) 

I'll open a PR to show you what I'd like. This is a consequent change so there won't be all the changes needed but only some to see if you agree with my vision or not.
